### PR TITLE
Add Cmdlet for generating new Unit Tests

### PR DESCRIPTION
**Pull request by joshcorr**
@niphlod  here is the code I promised you a few weeks back. This is a bit more polished than what I used, but it is still the main gist of what I did when I created the unit tests in mass. Still could have some improvements made, but provide it as a tool for future devs.

### CODE REVIEW

**Review by niphlod — APPROVED** [review]

**Comment by niphlod** [comment]
shout to @potatoqualitee and/or @wsmelton : I think this is a good addition here

**Comment by wsmelton** [comment]
I would only see this as one time use function. Considering that after 1.0 release we should require any submission of new function to have a test associated with it.

This can also just be turned into a snippet for vs code after all the current functions have test built for users to have easier access to templates.

**Comment by niphlod** [comment]
kudos for the snippet, it makes perfect sense.

**Comment by wsmelton** [comment]
Truthfully I would eventually like to drop this repository all together. Snippets I think are sufficient and we can also just add these to the wiki on dbatools repository so we don't have to maintain so much; especially as our standards are updated over time. I can see once we stop supporting PS 3/4 our templates will change a good bit to start moving toward newer code features with PS.

**Comment by potatoqualitee** [comment]
I use this repo, baw!

whoops, thank you, @joshcorr

**Pull request merged**
